[pytest]
markers =
    bgpOpen: Тесты для Open Message
    bgpNotification: Тесты для Notification Message
    bgpUpdate: Тесты для Update Message
    bfd: Тесты bfd
    rip: Тесты rip

filterwarnings =
    ignore::cryptography.utils.CryptographyDeprecationWarning:paramiko.*

addopts =
    -v
    --durations=10
    --strict-markers