src := rt-fib_fuzz_utils.c
obj := $(src-o-files)


fuzz_src := rt-fib_fuzz_positive_matches.c rt-fib_fuzz_negative_matches.c
fuzz_targets := $(fuzz_targets) $(fuzz-target-files)
fuzz_objs := $(fuzz_objs) $(src-o-files)
