name: Bird Fuzzing CI With Docker

on:
  push:
    branches:
      - CI-branch  

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t bird-fuzzing .

    - name: Run tests in Docker container
      run: |
        docker run --name bird-fuzzing-container bird-fuzzing:latest
        
    - name: Copy output file to GitHub Actions workspace
      run: |
        docker wait bird-fuzzing-container
        docker cp bird-fuzzing-container:/bird-fuzzing/output.txt ./output.txt
        mv ./output.txt $GITHUB_WORKSPACE/output.txt  

    - name: Upload test results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: fuzzing-results
        path: ./output.txt

    - name: Clean up Docker container
      run: |
        docker rm bird-fuzzing-container
